# Generated by Django 4.2.21 on 2025-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=100)),
                ('languages_used', models.CharField(default='', max_length=100)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment',
            field=models.ManyToManyField(blank=True, to='app.students'),
        ),
    ]
